# Generated by Django 4.2.21 on 2025-06-30 23:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('region', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('especialidad', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mecanico',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Producto', models.CharField(max_length=50)),
                ('Código_SKU', models.CharField(max_length=50, unique=True, verbose_name='Código SKU')),
                ('Proveedor', models.CharField(max_length=100)),
                ('Categoria', models.CharField(max_length=100)),
                ('Precio_Unitario', models.PositiveIntegerField(default=0)),
                ('Cantidad', models.PositiveIntegerField(default=0)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Fecha_Ingreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('usuario', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('tipo_combustible', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('electrico', 'Eléctrico'), ('hibrido', 'Híbrido')], max_length=20)),
                ('nro_chasis', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_vehiculo', models.CharField(choices=[('auto', 'Automóvil'), ('camioneta', 'Camioneta'), ('moto', 'Motocicleta'), ('bus', 'Bus'), ('camion', 'Camión')], max_length=20)),
            ],
            options={
                'db_table': 'vehiculo',
            },
            managers=[
                ('deleted_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='usuarios_usuario_set', related_query_name='usuario', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuarios_usuario_set', related_query_name='usuario', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuarios_usuario',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.PositiveIntegerField(help_text='Precio en pesos (sin decimales)', validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('duracion_estimada', models.DurationField()),
                ('descripcion', models.TextField(blank=True)),
                ('mecanicos', models.ManyToManyField(to='core.mecanico')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.AddField(
            model_name='mecanico',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='core.servicio'),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada')], default='pendiente', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mecanico')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.servicio')),
            ],
            options={
                'db_table': 'agenda',
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadMecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mecanico')),
            ],
            options={
                'verbose_name_plural': 'Disponibilidades de Mecánicos',
                'db_table': 'disponibilidad_mecanico',
                'unique_together': {('mecanico', 'dia_semana')},
            },
        ),
    ]
