# Generated by Django 4.2.21 on 2025-07-03 07:27

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('usuario', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('tipo_combustible', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('electrico', 'Eléctrico'), ('hibrido', 'Híbrido')], max_length=20)),
                ('nro_chasis', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_vehiculo', models.CharField(choices=[('auto', 'Automóvil'), ('camioneta', 'Camioneta'), ('moto', 'Motocicleta'), ('bus', 'Bus'), ('camion', 'Camión')], max_length=20)),
            ],
            options={
                'db_table': 'vehiculo',
            },
            managers=[
                ('deleted_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioComun',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('vehiculos', models.ManyToManyField(blank=True, to='core.vehiculo')),
            ],
            options={
                'db_table': 'usuario_comun',
            },
            bases=('login.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='usuarios_usuario_set', related_query_name='usuario', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuarios_usuario_set', related_query_name='usuario', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='mecanicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mecanico'),
        ),
        migrations.AddField(
            model_name='mecanico',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='core.servicio'),
        ),
        migrations.AddField(
            model_name='mecanico',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mecanico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disponibilidadmecanico',
            name='mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mecanico'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mecanico'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.servicio'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidadmecanico',
            unique_together={('mecanico', 'dia_semana')},
        ),
    ]
