# Generated by Django 4.2.21 on 2025-07-02 02:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('region', models.CharField(choices=[('arica', 'Arica y Parinacota'), ('tarapaca', 'Tarapacá'), ('antofagasta', 'Antofagasta'), ('atacama', 'Atacama'), ('coquimbo', 'Coquimbo'), ('valparaiso', 'Valparaíso'), ('metropolitana', 'Metropolitana de Santiago'), ('ohiggins', "Libertador General Bernardo O'Higgins"), ('maule', 'Maule'), ('nuble', 'Ñuble'), ('biobio', 'Biobío'), ('araucania', 'La Araucanía'), ('rios', 'Los Ríos'), ('lagos', 'Los Lagos'), ('aysen', 'Aysén del General Carlos Ibáñez del Campo'), ('magallanes', 'Magallanes y de la Antártica Chilena')], max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('especialidad', models.CharField(choices=[('lubricentro', 'Lubricentro'), ('electrico', 'Eléctrico'), ('vulcanizacion', 'Vulcanización'), ('mecanica', 'Mecánica'), ('pintura', 'Pintura')], max_length=50)),
                ('tipo', models.CharField(choices=[('taller', 'Taller'), ('particular', 'Particular')], max_length=20)),
            ],
            options={
                'db_table': 'mecanico',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.PositiveIntegerField(help_text='Precio en pesos (sin decimales)', validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('duracion_estimada', models.DurationField()),
                ('mecanicos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mecanico')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.AddField(
            model_name='mecanico',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='core.servicio'),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada')], default='pendiente', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mecanico')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.servicio')),
            ],
            options={
                'db_table': 'agenda',
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadMecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mecanico')),
            ],
            options={
                'verbose_name_plural': 'Disponibilidades de Mecánicos',
                'db_table': 'disponibilidad_mecanico',
                'unique_together': {('mecanico', 'dia_semana')},
            },
        ),
    ]
