# Generated by Django 4.2.21 on 2025-06-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mecanico_servicio_agenda_disponibilidadmecanico'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanico',
            name='servicios',
            field=models.ManyToManyField(to='core.servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='mecanicos',
            field=models.ManyToManyField(to='core.mecanico'),
        ),
    ]
