# Generated by Django 4.2.21 on 2025-07-03 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocomun',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='usuariocomun',
            name='vehiculos',
        ),
    ]
