# Generated by Django 4.2.21 on 2025-07-01 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mecanico_especialidad_alter_mecanico_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='mecanicos',
        ),
        migrations.AddField(
            model_name='servicio',
            name='mecanicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mecanico'),
        ),
    ]
