# Generated by Django 4.2.21 on 2025-06-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valoraciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracion',
            name='taller',
        ),
        migrations.DeleteModel(
            name='Taller',
        ),
    ]
